server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kezuler?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useLegacyDatetimeCode=false
    username: kezuler
    password: zpwnffj0824!

  jpa:
    show-sql: true
    hibernate:
#          ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

##tomcat ajp
tomcat:
  ajp:
    protocol: AJP/1.3
    port: 8009
    enabled: true

# app info
app:
  name: kezuler
  host: 54.180.134.149
#  host: 3.36.122.93
  jwt_header: Authorization
  jwt_prifix: "Bearer "
  jwt_access_time: 86400000
  jwt_refresh_time: 2592000000
  jwt_secret: kkezzulerr

  #  kakao_appkey: b2f5d4804c5ea11bf32f553ce2a5077c
  kakao_appkey: 0c7841de042de4b73e3a11c1af2f6671
  kakao_request_token_uri: https://kauth.kakao.com/oauth/authorize
  kakao_access_token_uri: https://kauth.kakao.com/oauth/token
  kakao_api_uri: https://kapi.kakao.com/v2
  kakao_admin_key: f4ada8f35c7dde65a105887d750dc1eb
  kakao_check_uri: https://kapi.kakao.com/v1/user/unlink

  ncp_sens_host: https://sens.apigw.ntruss.com
  ncp_sens_preurl: /alimtalk/v2/services/
  ncp_sens_channelid: "%40%EC%BC%80%EC%A5%B4%EB%9F%AC"
  ncp_sens_service: ncp:kkobizmsg:kr:2865972:kezuler
  ncp_sens_access_key: eRbEg7CQ9lwG1zhxZTiO
  ncp_sens_secret_key: Sr63M9tLEcQjxzrZMG7N0UdmIQHT2Y6ll0RG7I45

  google_cld_uri: https://www.googleapis.com/calendar/v3/calendars/
  google_client_id: 40603094782-sonac05jc2aumk75mug0949lfdiqivn0.apps.googleusercontent.com
  google_client_secret: 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
  google_request_token_uri: https://accounts.google.com/o/oauth2/auth
  google_access_token_uri: https://oauth2.googleapis.com/token
  google_authentication_uri: https://www.googleapis.com/oauth2/v3
  google_refresh_token_uri: https://accounts.google.com/o/oauth2/token
  google_revoke_uri: https://oauth2.googleapis.com/revoke


cloud:
  aws:
    credentials:
      accessKey: AKIAQ22CWYLEJNMB57IO
      secretKey: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: kezuler-images-dev/profileImage
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error


